version: "3.8"
services:
  mysqldb:
    image: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    networks:
      - mynetwork
  eureka:
    build: ./EurekaForMovieBooking
    restart: on-failure
    ports:
      - 8761:8761
    networks:
      - mynetwork	
  gateway:
    build: ./Gateway
    restart: on-failure
    ports:
      - 8080:8080
    networks:
      - mynetwork
  user:
    depends_on:
      - mysqldb
    build: ./UserBooking
    restart: on-failure
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/userbooking?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=root
    ports:
      - 8888:8888
    networks:
      - mynetwork
  admin:
    depends_on:
      - mysqldb
    build: ./MovieBookingApp
    restart: on-failure
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/booking?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=root
    ports:
      - 2222:2222
    networks:
      - mynetwork
networks:
  mynetwork:

