version: "3.8"
services:
  mysqldb:
    image: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    networks:
      - mynetwork
  eureka:
    build: ./EurekaForMovieBooking
    restart: on-failure
    ports:
      - 8761:8761
    networks:
      - mynetwork	
  gateway:
    build: ./Gateway
    restart: on-failure
    environment:
       SPRING_APPLICATION_JSON: '{
        "eureka.client.service-url.defaultZone" : "http://eureka:8761/eureka"
       }'
    ports:
      - 3333:3333
    networks:
      - mynetwork
  user:
    depends_on:
      - mysqldb
    build: ./UserBooking
    restart: on-failure
    environment:
      SPRING_APPLICATION_JSON: '{
        "eureka.client.service-url.defaultZone" : "http://eureka:8761/eureka",
        "spring.datasource.url" : "jdbc:mysql://mysqldb:3306/user?createDatabaseIfNotExist=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root"
      }'
   
      
    ports:
      - 8888:8888
    networks:
      - mynetwork
  admin:
    depends_on:
      - mysqldb
    build: ./MovieBookingApp
    restart: on-failure
    environment:
      SPRING_APPLICATION_JSON: '{
        "eureka.client.service-url.defaultZone" : "http://eureka:8761/eureka",
        "spring.datasource.url" : "jdbc:mysql://mysqldb:3306/admin?createDatabaseIfNotExist=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root"
      }'
    ports:
      - 2222:2222
    networks:
      - mynetwork
networks:
  mynetwork: