spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: admin
          uri: lb://admin/ # Use the name of the microservice as registered in your service registry (e.g., Eureka)
          predicates:
            - Path=/admin/**
        - id: user
          uri: lb://user/ # Use the name of the microservice as registered in your service registry (e.g., Eureka)
          predicates:
            - Path=/user/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 3333     
      
      

                  
